### PR TITLE
Feat/create use candy machine hook

### PR DESCRIPTION
**Pull request by Lawal-create**

### CODE REVIEW

**Comment by salisbuk7897** [comment]
for the verify transaction class, I'm not sure what it does but if it is verifying the payment of sol, this is not the place to implement it

**Comment by Lawal-create** [comment]
Alright. I would remove it but this PR is not ready for review at the moment.  Raised it, so that anyone could view my progress.

**Comment by salisbuk7897** [comment]
okay. I get it you want to make progress... the good progress to make is to start a transaction class that uses solana pay post request to process transaction. use solana pay find reference to verify transaction

**Review by salisbuk7897 — APPROVED** [review]

**Comment by salisbuk7897** [comment]
Good Job

**Pull request merged**
